### PR TITLE
Library-level Exceptions, result.exception

### LINKED ISSUE #319: custom library-level exceptions
As pointed out in #177
>  we could solve this by creating our own kind of exceptions so that we can handle them cleaner internally.

It would also make it easier / possible for users to have different logic for different errors, i.e. ignore network related issues when using the cache. 

Worth noting that without something like #201, it will be easy for a user making heavy use of the offline queue to shoot themselves in the foot by pretending mutations succeeded when they didn't and will never run again.

### LINKED ISSUE #380: SocketException is crashing application
**Describe the bug**
I cannot handle the SocketException error.

**To Reproduce**
1. Go to https://github.com/ryankauk/graphqlFlutterSocketException
2. Install and run flutter application. (I'm using VsCode Start Debugging using Flutter extension)
3. You'll see the error thrown

**Expected behavior**
The error should be at the minimum be able to handled in try catch statement. Stated by the package it should be added to graphql errors.

**Screenshots**
When using try catch
Screen Shot 2019-08-13 at 2 30 48 PM

Full error without try catch
Screen Shot 2019-08-13 at 2 30 17 PM

**Desktop (please complete the following information):**
 - OS: macOS Mojave 
 - Version 10.14.4

### PR DESCRIPTION
**Pull request by micimize**
closes #319
closes #380

### Breaking changes

- Broke `QueryResult.errors` in order to wrap it in `OperationException`

#### Fixes / Enhancements

* introduced distinction between `GraphqlErrors` and `ClientExceptions`
* make `SocketExceptions` intelligible via `NetworkException`
* `OperationException` `QueryResult.exception` that supports both
  * `clientException` such as `NetworkException` and `CacheMissException`
  * and `graphqlErrors`
* added paginating tab to graphql example

#### Docs
Added to readme:

##### Exceptions

If there were problems encountered during a query or mutation, the `QueryResult` will have an `OperationException` in the `exception` field:

```dart
class OperationException implements Exception {
  /// Any graphql errors returned from the operation
  List<GraphQLError> graphqlErrors = [];

  /// Errors encountered during execution such as network or cache errors
  ClientException clientException;
}
```

Example usage:

```dart
if (result.hasException) {
    if (result.exception.clientException is NetworkException) {
        // handle network issues, maybe
    }
    return Text(result.exception.toString())
}
```

### CODE REVIEW

**Comment by micimize** [comment]
@HofmannZ please take a [quick look](https://github.com/zino-app/graphql-flutter/pull/393/files?file-filters%5B%5D=.dart) at this, as I think it's a significant api design change.

File: examples/starwars/lib/episode/hero_query.dart [hunk 1]
```diff
@@ -36,15 +36,15 @@ class HeroForEpisode extends StatelessWidget {
...
-        }
-
         if (result.loading) {
-          return Center(
-            child: const CircularProgressIndicator(),
+          return const Center(
+            child: CircularProgressIndicator(),
           );
         }
+
```
Comment (HofmannZ) [inline examples/starwars/lib/episode/hero_query.dart]: Would always check for errors before checking for loading. To abound infinite loading screens when actually an error had occurred.

File: examples/starwars/lib/reviews/force_rebroadcast.dart [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+import 'package:graphql_flutter/graphql_flutter.dart';
+
+class ForceRebroadcast extends StatelessWidget {
+  @override
+  Widget build(BuildContext context) {
+    return Mutation(
+      options: MutationOptions(
+        document: r'''
+        mutation Rebroadcast {
+        }
```
Comment (HofmannZ) [inline examples/starwars/lib/reviews/force_rebroadcast.dart]: Is this valid query language?

File: packages/graphql/lib/src/core/query_manager.dart [hunk 3]
```diff
@@ -36,12 +36,6 @@ class QueryManager {
   Map<String, ObservableQuery> queries = <String, ObservableQuery>{};
 
   ObservableQuery watchQuery(WatchQueryOptions options) {
-    if (options.document == null) {
```
Comment (HofmannZ) [inline packages/graphql/lib/src/core/query_manager.dart]: Can we safely drop this?

File: packages/graphql/lib/src/core/query_manager.dart [hunk 4]
```diff
@@ -120,6 +114,9 @@ class QueryManager {
         );
       }
 
+      // TODO this should never happen right?
+      // if there is an error reaching the server, there should be an error thrown,
+      // if not, data should not be null.
       if (fetchResult.data == null &&
```
Comment (HofmannZ) [inline packages/graphql/lib/src/core/query_manager.dart]: Yeah that’s right!

File: packages/graphql/lib/src/core/query_options.dart [hunk 5]
```diff
@@ -92,8 +92,8 @@ class QueryOptions extends BaseOptions {
   QueryOptions({
     @required String document,
     Map<String, dynamic> variables,
-    FetchPolicy fetchPolicy = FetchPolicy.cacheFirst,
-    ErrorPolicy errorPolicy = ErrorPolicy.none,
+    FetchPolicy fetchPolicy,
```
Comment (HofmannZ) [inline packages/graphql/lib/src/core/query_options.dart]: Why take out these defaults?

File: packages/graphql/lib/src/core/raw_operation_data.dart [hunk 6]
```diff
@@ -13,7 +13,8 @@ class RawOperationData {
     @required this.document,
     Map<String, dynamic> variables,
     String operationName,
-  })  : _operationName = operationName,
+  })  : assert(document != null),
```
Comment (HofmannZ) [inline packages/graphql/lib/src/core/raw_operation_data.dart]: At the comment earlier we had a readable error. No we have an failing assertion on the `RawOperation` that might be a load harder to debug for someone new to the library.

File: packages/graphql/lib/src/exceptions/_base_exceptions.dart [hunk 7]
```diff
@@ -0,0 +1,46 @@
+abstract class ClientException implements Exception {
+  String get message;
+}
+
+//
+// Cache exceptions
```
Comment (HofmannZ) [inline packages/graphql/lib/src/exceptions/_base_exceptions.dart]: Nice to have all the errors together! 👍🏼

File: examples/starwars/lib/reviews/force_rebroadcast.dart (hunk 2 above)
Comment (micimize) [reply examples/starwars/lib/reviews/force_rebroadcast.dart]: no - I'm removing it as it was just a utility for testing some pagination issues.

File: packages/graphql/lib/src/core/query_manager.dart (hunk 3 above)
Comment (micimize) [reply packages/graphql/lib/src/core/query_manager.dart]: yes, because of `assert(document != null)` in `RawOperationData`

File: packages/graphql/lib/src/core/query_options.dart (hunk 5 above)
Comment (micimize) [reply packages/graphql/lib/src/core/query_options.dart]: Defaults are now configurable in `GraphQLClient.defaultPolicies` (#398), so they need to be `null` to be overridden later. So this is actually more of a fix 😅

File: packages/graphql/lib/src/core/raw_operation_data.dart (hunk 6 above)
Comment (micimize) [reply packages/graphql/lib/src/core/raw_operation_data.dart]: added a the message back in on failed assertion

**Comment by micimize** [comment]
@HofmannZ changes made and questions answered 👆

**Comment by HofmannZ** [comment]
Should we bundle this with #414, so we only ship one breaking change?

**Comment by mainawycliffe** [comment]
> Should we bundle this with #414, so we only ship one breaking change?

I think this is better, so we could have a milestone for the next major version and see what major API changes we could fit it in.

**Comment by micimize** [comment]
> Should we bundle this with #414, so we only ship one breaking change?

I agree, but only in terms of doing so when we exit `beta` (merge into `master`)

**Comment by HofmannZ** [comment]
@micimize, @mainawycliffe Agreed, I’ve pushed some fixed to the pipeline, so we should see releases more often.
